spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
#    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&characterEncoding=utf-8
      username: root
      driver-class-name: com.mysql.jdbc.Driver